apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezio
  labels:
    desc: ezio-app-deployment
spec:
  selector:
    matchLabels:
      app: ezio
  replicas: 3
  template:
    metadata:
      labels:
        app: ezio
    spec:
      containers:
      - name: ezio-main
        image: docker.io/akkiankit/ezio:latest
        ports:
        - containerPort: 8000
