version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  frontend:
    build: ./frontend
    container_name: nginx_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
